# 2) Write JSON body to a file
cat > members.json <<'JSON'
[
  {
    "Title": "Miss",
    "lastName": "Beny",
    "middleName": "",
    "firstName": "Anglina",
    "fatherName": "Lt. Mr George Beny",
    "spouseName": "",
    "gender": "Female",
    "dob": "21-Jan-1993",
    "age": "31",
    "maritalStatus": "Unmarried",
    "dateOfMarriage": "",
    "yearsOfMarriage": "",
    "Address": "Sector5/G/84, Kudi Bhagtasni Housing Board, BasniI, Jodhpur.",
    "contact": "9799367755",
    "email": "",
    "baptised": "Yes",
    "baptisedDate": "",
    "confirmed": "Yes",
    "confirmationDate": "04-Dec-2005",
    "fullMember": "Yes",
    "nonResidentMember": "",
    "preparatoryMember": "",
    "selfDependent": "",
    "status": "Active",
    "inactiveReason": "",
    "inactiveSince": ""
  },
  {
    "Title": "Mr",
    "lastName": "Beny",
    "middleName": "",
    "firstName": "Aman",
    "fatherName": "Lt.  Mr George Beny",
    "spouseName": "",
    "gender": "Male",
    "dob": "14-Apr-1996",
    "age": "27",
    "maritalStatus": "Unmarried",
    "dateOfMarriage": "",
    "yearsOfMarriage": "",
    "Address": "Sector5/G/84, Kudi Bhagtasni Housing Board, BasniI, Jodhpur.",
    "contact": "9799367755",
    "email": "",
    "baptised": "Yes",
    "baptisedDate": "",
    "confirmed": "Yes",
    "confirmationDate": "18-Mar-2012",
    "fullMember": "Yes",
    "nonResidentMember": "",
    "preparatoryMember": "",
    "selfDependent": "",
    "status": "Active",
    "inactiveReason": "",
    "inactiveSince": ""
  },
  {
    "Title": "Miss",
    "lastName": "Beny",
    "middleName": "",
    "firstName": "Arshi",
    "fatherName": "Lt.  Mr George Beny",
    "spouseName": "",
    "gender": "Female",
    "dob": "06-Aug-1989",
    "age": "34",
    "maritalStatus": "Divorced",
    "dateOfMarriage": "",
    "yearsOfMarriage": "",
    "Address": "Sector5/G/84, Kudi Bhagtasni Housing Board, BasniI, Jodhpur.",
    "contact": "9799888389",
    "email": "",
    "baptised": "Yes",
    "baptisedDate": "",
    "confirmed": "Yes",
    "confirmationDate": "04-Dec-2005",
    "fullMember": "Yes",
    "nonResidentMember": "",
    "preparatoryMember": "",
    "selfDependent": "Yes",
    "status": "Active",
    "inactiveReason": "",
    "inactiveSince": ""
  }
]
JSON

# 3) Call POST API with JSON file
curl -X POST "http://localhost:8080/members" \
  -H "Content-Type: application/json" \
  -d @members.json